spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/etic_system?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Mexico_City&zeroDateTimeBehavior=CONVERT_TO_NULL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:etic_local}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:etic_local_password}
app.datasource.licensing.url=${LICENSE_DATASOURCE_URL:jdbc:mysql://localhost:3307/license_system?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Mexico_City&zeroDateTimeBehavior=CONVERT_TO_NULL}
app.datasource.licensing.username=${LICENSE_DATASOURCE_USERNAME:etic_local}
app.datasource.licensing.password=${LICENSE_DATASOURCE_PASSWORD:etic_local_password}

spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
