spring.application.name=back-etic-system
server.port=${SERVER_PORT:8080}
server.forward-headers-strategy=framework
spring.profiles.default=dev
app.storage.path=${APP_STORAGE_PATH:storage}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
