spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://etic-db:3306/etic_system?useSSL=false&serverTimezone=America/Mexico_City&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=CONVERT_TO_NULL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:etic_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
