package com.etic.system.licensing.security;

import com.etic.system.licensing.application.port.LicensingPersistencePort;
import com.etic.system.licensing.config.LicensingSecurityProperties;
import com.etic.system.licensing.domain.*;
import com.etic.system.shared.domain.exception.BusinessValidationException;
import com.etic.system.shared.domain.exception.ResourceNotFoundException;
import java.nio.charset.StandardCharsets;
import java.security.*;
import java.security.interfaces.ECPublicKey;
import java.security.spec.X509EncodedKeySpec;
import java.sql.Timestamp;
import java.time.*;
import java.util.*;
import javax.sql.DataSource;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.jdbc.core.namedparam.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class DeviceSecurityService {
	private static final SecureRandom RANDOM=new SecureRandom();
	private static final char[] ENROLLMENT_ALPHABET="23456789ABCDEFGHJKLMNPQRSTUVWXYZ".toCharArray();
	private final NamedParameterJdbcTemplate jdbc;
	private final NamedParameterJdbcTemplate eticJdbc;
	private final LicensingPersistencePort persistence;
	private final LicensingSecurityProperties properties;
	private final OfflineCredentialService credentials;
	public DeviceSecurityService(@Qualifier("licensingJdbc") NamedParameterJdbcTemplate jdbc,@Qualifier("namedParameterJdbcTemplate") NamedParameterJdbcTemplate eticJdbc,LicensingPersistencePort persistence,LicensingSecurityProperties properties,OfflineCredentialService credentials){this.jdbc=jdbc;this.eticJdbc=eticJdbc;this.persistence=persistence;this.properties=properties;this.credentials=credentials;}

	@Transactional("licensingTransactionManager")
	public ManualDeviceCreated createManual(String name,String manufacturer,String model,String androidVersion,String initialStatus,String notes,String actorId){
		required(name,"El nombre del dispositivo es obligatorio");String status=initialStatus==null||initialStatus.isBlank()?"PENDING":initialStatus.trim().toUpperCase(Locale.ROOT);if(!Set.of("PENDING","SUSPENDED").contains(status))throw new BusinessValidationException("El estado inicial debe ser PENDING o SUSPENDED");
		String id=uuid();LocalDateTime now=LocalDateTime.now();jdbc.update("INSERT INTO licensed_devices(Id_Device,Device_UUID,Origin,Display_Name,Manufacturer,Model,Android_Version,Status,Notes,Registered_At,Updated_By) VALUES(:id,:uuid,'MANUAL',:name,:manufacturer,:model,:android,:status,:notes,:now,:actor)",new MapSqlParameterSource().addValue("id",id).addValue("uuid",id).addValue("name",name.trim()).addValue("manufacturer",trim(manufacturer)).addValue("model",trim(model)).addValue("android",trim(androidVersion)).addValue("status",status).addValue("notes",trim(notes)).addValue("now",Timestamp.valueOf(now)).addValue("actor",actorId));
		EnrollmentCode code=createEnrollmentCode(id,actorId);event("DEVICE_CREATED_MANUAL","SUCCESS",id,null,null,null,null,null,null,actorId);return new ManualDeviceCreated(device(id),code.code(),code.expiresAt());
	}

	@Transactional("licensingTransactionManager")
	public EnrollmentCode regenerateEnrollmentCode(String deviceId,String actorId){LicensedDevice device=device(deviceId);if("REVOKED".equals(device.status()))throw new BusinessValidationException("Un dispositivo revocado no puede recibir códigos de enrolamiento");if(device.publicKeyFingerprint()!=null)throw new BusinessValidationException("El dispositivo ya está vinculado; requiere un proceso explícito de re-enrolamiento");jdbc.update("UPDATE device_enrollment_codes SET Revoked_At=:now WHERE Id_Device=:id AND Used_At IS NULL AND Revoked_At IS NULL",Map.of("now",Timestamp.valueOf(LocalDateTime.now()),"id",deviceId));return createEnrollmentCode(deviceId,actorId);}

	@Transactional("licensingTransactionManager")
	public LicensedDevice registerAuto(DeviceIdentity input,String remoteIp){
		ApplicationIdentity app=activeApplication(input.packageName());KeyIdentity key=parsePublicKey(input.publicKey());ensureFingerprintAvailable(key.fingerprint(),null);String id=uuid();LocalDateTime now=LocalDateTime.now();
		jdbc.update("INSERT INTO licensed_devices(Id_Device,Device_UUID,Origin,Display_Name,Manufacturer,Model,Android_Version,Status,Android_ID,Package_Name,App_Version,Public_Key_Algorithm,Public_Key,Public_Key_Fingerprint,Key_Security_Level,Attestation_Available,Attestation_Verified,Registered_At,Enrolled_At) VALUES(:id,:uuid,'AUTO',:name,:manufacturer,:model,:android,'PENDING',:androidId,:packageName,:appVersion,'EC',:publicKey,:fingerprint,:level,:attestation,FALSE,:now,:now)",identityParams(id,input,key,now));
		event("DEVICE_REGISTERED_AUTO","SUCCESS",id,app.id(),null,null,input.appVersion(),remoteIp,null,null);return device(id);
	}

	@Transactional("licensingTransactionManager")
	public LicensedDevice enroll(String enrollmentCode,DeviceIdentity input,String remoteIp){
		required(enrollmentCode,"El código de enrolamiento es obligatorio");String hash=sha256(normalizeCode(enrollmentCode).getBytes(StandardCharsets.UTF_8));EnrollmentRow enrollment=findEnrollment(hash);LocalDateTime now=LocalDateTime.now();
		if(enrollment.revokedAt()!=null)throw new BusinessValidationException("El código de enrolamiento fue revocado");if(enrollment.usedAt()!=null)throw new BusinessValidationException("El código de enrolamiento ya fue utilizado");if(enrollment.expiresAt().isBefore(now))throw new BusinessValidationException("El código de enrolamiento expiró");
		LicensedDevice current=device(enrollment.deviceId());if("REVOKED".equals(current.status()))throw new BusinessValidationException("El dispositivo está revocado");if(current.publicKeyFingerprint()!=null)throw new BusinessValidationException("El dispositivo ya está vinculado a una clave pública");ApplicationIdentity app=activeApplication(input.packageName());KeyIdentity key=parsePublicKey(input.publicKey());ensureFingerprintAvailable(key.fingerprint(),current.id());
		int used=jdbc.update("UPDATE device_enrollment_codes SET Used_At=:now WHERE Id_Enrollment=:id AND Used_At IS NULL AND Revoked_At IS NULL",Map.of("now",Timestamp.valueOf(now),"id",enrollment.id()));if(used!=1)throw new BusinessValidationException("El código de enrolamiento ya no está disponible");
		MapSqlParameterSource p=identityParams(current.id(),input,key,now);p.addValue("now",Timestamp.valueOf(now));jdbc.update("UPDATE licensed_devices SET Status='ACTIVE',Android_ID=:androidId,Manufacturer=COALESCE(:manufacturer,Manufacturer),Model=COALESCE(:model,Model),Android_Version=COALESCE(:android,Android_Version),Package_Name=:packageName,App_Version=:appVersion,Public_Key_Algorithm='EC',Public_Key=:publicKey,Public_Key_Fingerprint=:fingerprint,Key_Security_Level=:level,Attestation_Available=:attestation,Attestation_Verified=FALSE,Enrolled_At=:now,Updated_At=:now WHERE Id_Device=:id",p);
		event("DEVICE_ENROLLED","SUCCESS",current.id(),app.id(),null,null,input.appVersion(),remoteIp,null,null);return device(current.id());
	}

	@Transactional("licensingTransactionManager")
	public LicensedDevice changeStatus(String deviceId,String status,String actorId){LicensedDevice current=device(deviceId);String target=status.toUpperCase(Locale.ROOT);if(!Set.of("ACTIVE","SUSPENDED","REVOKED").contains(target))throw new BusinessValidationException("Estado de dispositivo no permitido");if(target.equals("ACTIVE")&&current.publicKeyFingerprint()==null)throw new BusinessValidationException("El dispositivo debe enrolarse antes de activarse");jdbc.update("UPDATE licensed_devices SET Status=:status,Updated_At=:now,Updated_By=:actor WHERE Id_Device=:id",Map.of("status",target,"now",Timestamp.valueOf(LocalDateTime.now()),"actor",actorId,"id",deviceId));event(target.equals("ACTIVE")?"DEVICE_ACTIVATED":"DEVICE_"+target,"SUCCESS",deviceId,null,null,null,null,null,null,actorId);return device(deviceId);}

	@Transactional("licensingTransactionManager")
	public Challenge createChallenge(String deviceId,String remoteIp){LicensedDevice device=device(deviceId);if(!"ACTIVE".equals(device.status())||device.publicKeyFingerprint()==null)throw new BusinessValidationException("El dispositivo no está activo y enrolado");byte[] nonce=new byte[32];RANDOM.nextBytes(nonce);String value=Base64.getUrlEncoder().withoutPadding().encodeToString(nonce);String id=uuid();LocalDateTime now=LocalDateTime.now();LocalDateTime expires=now.plusMinutes(properties.getChallengeValidityMinutes());jdbc.update("INSERT INTO device_challenges(Id_Challenge,Id_Device,Nonce_Value,Nonce_Hash,Expires_At,Created_At) VALUES(:id,:device,:nonce,:hash,:expires,:now)",Map.of("id",id,"device",deviceId,"nonce",value,"hash",sha256(nonce),"expires",Timestamp.valueOf(expires),"now",Timestamp.valueOf(now)));return new Challenge(id,deviceId,value,expires);}

	@Transactional("licensingTransactionManager")
	public Verification verifyChallenge(String deviceId,String challengeId,String signatureValue,String remoteIp){ChallengeRow challenge=findChallenge(challengeId,deviceId);LocalDateTime now=LocalDateTime.now();if(challenge.usedAt()!=null)throw new BusinessValidationException("El challenge ya fue utilizado");if(challenge.expiresAt().isBefore(now))throw new BusinessValidationException("El challenge expiró");boolean verified=verifySignature(challenge.publicKey(),challenge.nonce(),signatureValue);if(!verified){event("CHALLENGE_VERIFIED","REJECTED",deviceId,null,null,null,null,remoteIp,"Firma inválida",null);throw new BusinessValidationException("La firma del challenge no es válida");}int changed=jdbc.update("UPDATE device_challenges SET Used_At=:now WHERE Id_Challenge=:id AND Used_At IS NULL",Map.of("now",Timestamp.valueOf(now),"id",challengeId));if(changed!=1)throw new BusinessValidationException("El challenge ya no está disponible");jdbc.update("UPDATE licensed_devices SET Last_Validation_At=:now WHERE Id_Device=:device",Map.of("now",Timestamp.valueOf(now),"device",deviceId));event("CHALLENGE_VERIFIED","SUCCESS",deviceId,null,null,null,null,remoteIp,null,null);return new Verification(challengeId,deviceId,true,now);}

	public OperationalLicense validateLicense(String licenseId,String deviceId,String appVersion,String remoteIp){try{LicenseRow license=usableLicense(licenseId,deviceId);event("LICENSE_VALIDATED","SUCCESS",deviceId,license.applicationId(),license.userId(),licenseId,appVersion,remoteIp,null,null);return new OperationalLicense(true,"READY",licenseId,deviceId,license.applicationId(),license.userId(),license.validUntil());}catch(RuntimeException ex){event("LICENSE_REJECTED","REJECTED",null,null,null,null,appVersion,remoteIp,ex.getMessage(),null);return new OperationalLicense(false,"REJECTED",licenseId,deviceId,null,null,null);}}

	@Transactional("licensingTransactionManager")
	public LicenseSession openSession(DeviceIdentity input,String userId,String remoteIp){
		ApplicationIdentity app=activeApplication(input.packageName());
		KeyIdentity key=parsePublicKey(input.publicKey());
		AccessRow access=jdbc.query("SELECT Valid_Until,Max_Devices FROM user_application_access WHERE Id_Usuario=:user AND Id_Application=:app AND Status='ACTIVE' AND Valid_From<=CURRENT_DATE AND (Valid_Until IS NULL OR Valid_Until>=CURRENT_DATE) FOR UPDATE",Map.of("user",userId,"app",app.id()),(r,n)->new AccessRow(r.getDate("Valid_Until")==null?null:r.getDate("Valid_Until").toLocalDate(),r.getInt("Max_Devices"))).stream().findFirst().orElseThrow(()->new BusinessValidationException("Este usuario no cuenta con una licencia activa."));
		LicensedDevice device=jdbc.query("SELECT Id_Device FROM licensed_devices WHERE Public_Key_Fingerprint=:fingerprint",Map.of("fingerprint",key.fingerprint()),(r,n)->device(r.getString(1))).stream().findFirst().orElse(null);
		if(device!=null&&Set.of("REVOKED","SUSPENDED","INACTIVE").contains(device.status()))throw new BusinessValidationException("REVOKED".equals(device.status())?"La licencia de este dispositivo fue revocada.":"Este dispositivo no está autorizado para utilizar ETIC.");
		Integer used=jdbc.queryForObject("SELECT COUNT(DISTINCT l.Id_Device) FROM licenses l JOIN licensed_devices d ON d.Id_Device=l.Id_Device WHERE l.Id_Application=:app AND l.Id_Usuario=:user AND l.Status='ACTIVE' AND l.Valid_From<=CURRENT_DATE AND l.Valid_Until>=CURRENT_DATE AND d.Status='ACTIVE'"+(device==null?"":" AND l.Id_Device<>:device"),device==null?new MapSqlParameterSource().addValue("app",app.id()).addValue("user",userId):new MapSqlParameterSource().addValue("app",app.id()).addValue("user",userId).addValue("device",device.id()),Integer.class);
		if(used!=null&&used>=access.maxDevices())throw new BusinessValidationException("Se alcanzó el número máximo de dispositivos autorizados.");
		if(device==null){device=registerAuto(input,remoteIp);jdbc.update("UPDATE licensed_devices SET Status='ACTIVE',Updated_At=:now WHERE Id_Device=:id",Map.of("now",Timestamp.valueOf(LocalDateTime.now()),"id",device.id()));device=device(device.id());}
		String deviceId=device.id();
		String licenseId=jdbc.query("SELECT Id_License FROM licenses WHERE Id_Application=:app AND Id_Device=:device AND Id_Usuario=:user AND Status='ACTIVE' AND Valid_From<=CURRENT_DATE AND Valid_Until>=CURRENT_DATE",Map.of("app",app.id(),"device",deviceId,"user",userId),(r,n)->r.getString(1)).stream().findFirst().orElse(null);
		if(licenseId==null){licenseId=uuid();LocalDate until=access.validUntil()==null?LocalDate.of(9999,12,31):access.validUntil();jdbc.update("INSERT INTO licenses(Id_License,Id_Application,Id_Device,Id_Usuario,Valid_From,Valid_Until,Status,Created_At,Created_By) VALUES(:id,:app,:device,:user,CURRENT_DATE,:until,'ACTIVE',:now,:user)",new MapSqlParameterSource().addValue("id",licenseId).addValue("app",app.id()).addValue("device",deviceId).addValue("user",userId).addValue("until",java.sql.Date.valueOf(until)).addValue("now",Timestamp.valueOf(LocalDateTime.now())));}
		return new LicenseSession(licenseId,deviceId,key.fingerprint(),System.currentTimeMillis());
	}

	@Transactional("licensingTransactionManager")
	public OfflineCredential refreshCredential(String licenseId,String deviceId,String challengeId,String appVersion,String remoteIp){LicenseRow license=usableLicense(licenseId,deviceId);ChallengeRow challenge=findChallenge(challengeId,deviceId);if(challenge.usedAt()==null)throw new BusinessValidationException("El challenge todavía no fue verificado");if(challenge.credentialIssuedAt()!=null)throw new BusinessValidationException("El challenge ya emitió una credencial");LocalDateTime now=LocalDateTime.now();LocalDate offlineUntil=LocalDate.now().plusDays(properties.getOfflineValidityDays());if(offlineUntil.isAfter(license.validUntil()))offlineUntil=license.validUntil();Map<String,Object> claims=new LinkedHashMap<>();claims.put("licenseId",licenseId);claims.put("deviceId",deviceId);claims.put("deviceFingerprint",license.deviceFingerprint());if(license.userId()!=null)claims.put("userId",license.userId());claims.put("applicationId",license.applicationId());claims.put("packageName",license.packageName());claims.put("issuedAt",now.toString());claims.put("offlineValidUntil",offlineUntil.toString());claims.put("licenseValidUntil",license.validUntil().toString());String credential=credentials.issue(claims);int changed=jdbc.update("UPDATE device_challenges SET Credential_Issued_At=:now WHERE Id_Challenge=:id AND Credential_Issued_At IS NULL",Map.of("now",Timestamp.valueOf(now),"id",challengeId));if(changed!=1)throw new BusinessValidationException("El challenge ya no está disponible para emitir credencial");event("LICENSE_REFRESHED","SUCCESS",deviceId,license.applicationId(),license.userId(),licenseId,appVersion,remoteIp,null,null);return new OfflineCredential(credential,properties.getSigningKeyId(),now,offlineUntil,license.validUntil());}

	public static boolean verifySignature(String publicKeyValue,String nonceValue,String signatureValue){try{PublicKey key=parseEcPublicKey(publicKeyValue);Signature signature=Signature.getInstance("SHA256withECDSA");signature.initVerify(key);signature.update(Base64.getUrlDecoder().decode(nonceValue));return signature.verify(Base64.getDecoder().decode(signatureValue));}catch(GeneralSecurityException|IllegalArgumentException ex){return false;}}

	private EnrollmentCode createEnrollmentCode(String deviceId,String actorId){for(int attempt=0;attempt<10;attempt++){String code=randomEnrollmentCode();String hash=sha256(code.getBytes(StandardCharsets.UTF_8));Integer count=jdbc.queryForObject("SELECT COUNT(*) FROM device_enrollment_codes WHERE Code_Hash=:hash",Map.of("hash",hash),Integer.class);if(count!=null&&count>0)continue;LocalDateTime now=LocalDateTime.now();LocalDateTime expires=now.plusHours(properties.getEnrollmentValidityHours());jdbc.update("INSERT INTO device_enrollment_codes(Id_Enrollment,Id_Device,Code_Hash,Expires_At,Created_At,Created_By) VALUES(:id,:device,:hash,:expires,:now,:actor)",Map.of("id",uuid(),"device",deviceId,"hash",hash,"expires",Timestamp.valueOf(expires),"now",Timestamp.valueOf(now),"actor",actorId));return new EnrollmentCode(code,expires);}throw new IllegalStateException("No fue posible generar un código de enrolamiento único");}
	private String randomEnrollmentCode(){StringBuilder value=new StringBuilder("ETIC-");for(int i=0;i<8;i++){if(i==4)value.append('-');value.append(ENROLLMENT_ALPHABET[RANDOM.nextInt(ENROLLMENT_ALPHABET.length)]);}return value.toString();}
	private EnrollmentRow findEnrollment(String hash){return jdbc.query("SELECT * FROM device_enrollment_codes WHERE Code_Hash=:hash",Map.of("hash",hash),(r,n)->new EnrollmentRow(r.getString("Id_Enrollment"),r.getString("Id_Device"),r.getTimestamp("Expires_At").toLocalDateTime(),time(r.getTimestamp("Used_At")),time(r.getTimestamp("Revoked_At")))).stream().findFirst().orElseThrow(()->new BusinessValidationException("Código de enrolamiento inválido"));}
	private ChallengeRow findChallenge(String challengeId,String deviceId){return jdbc.query("SELECT c.*,d.Public_Key FROM device_challenges c JOIN licensed_devices d ON d.Id_Device=c.Id_Device WHERE c.Id_Challenge=:id AND c.Id_Device=:device",Map.of("id",challengeId,"device",deviceId),(r,n)->new ChallengeRow(r.getString("Nonce_Value"),r.getString("Public_Key"),r.getTimestamp("Expires_At").toLocalDateTime(),time(r.getTimestamp("Used_At")),time(r.getTimestamp("Credential_Issued_At")))).stream().findFirst().orElseThrow(()->new BusinessValidationException("Challenge inválido"));}
	private LicenseRow usableLicense(String licenseId,String deviceId){LicenseRow value=jdbc.query("SELECT l.Id_Application,l.Id_Usuario,l.Valid_Until,a.Package_Name,a.Licensing_Mode,d.Public_Key_Fingerprint FROM licenses l JOIN licensed_applications a ON a.Id_Application=l.Id_Application JOIN licensed_devices d ON d.Id_Device=l.Id_Device WHERE l.Id_License=:license AND l.Id_Device=:device AND l.Status='ACTIVE' AND l.Valid_From<=CURRENT_DATE AND l.Valid_Until>=CURRENT_DATE AND a.Status='ACTIVE' AND d.Status='ACTIVE' AND d.Package_Name=a.Package_Name",Map.of("license",licenseId,"device",deviceId),(r,n)->new LicenseRow(r.getString("Id_Application"),r.getString("Id_Usuario"),r.getDate("Valid_Until").toLocalDate(),r.getString("Package_Name"),LicensingMode.valueOf(r.getString("Licensing_Mode")),r.getString("Public_Key_Fingerprint"))).stream().findFirst().orElseThrow(()->new BusinessValidationException("La licencia no está operativa"));if(value.mode()==LicensingMode.USER_DEVICE){if(value.userId()==null||!activeUser(value.userId()))throw new BusinessValidationException("El usuario no existe o está inactivo");}return value;}
	private boolean activeUser(String id){Integer count=eticJdbc.queryForObject("SELECT COUNT(*) FROM usuarios WHERE Id_Usuario=:id AND Estatus='Activo'",Map.of("id",id),Integer.class);return count!=null&&count>0;}
	private ApplicationIdentity activeApplication(String packageName){required(packageName,"El package name es obligatorio");return jdbc.query("SELECT Id_Application,Licensing_Mode FROM licensed_applications WHERE Package_Name=:package AND Status='ACTIVE'",Map.of("package",packageName.trim()),(r,n)->new ApplicationIdentity(r.getString(1),LicensingMode.valueOf(r.getString(2)))).stream().findFirst().orElseThrow(()->new BusinessValidationException("La aplicación no existe o está inactiva"));}
	private KeyIdentity parsePublicKey(String value){try{PublicKey key=parseEcPublicKey(value);if(!(key instanceof ECPublicKey ec)||ec.getParams().getOrder().bitLength()!=256)throw new BusinessValidationException("La clave pública debe usar EC P-256");return new KeyIdentity(Base64.getEncoder().encodeToString(key.getEncoded()),sha256(key.getEncoded()));}catch(GeneralSecurityException|IllegalArgumentException ex){throw new BusinessValidationException("La clave pública EC P-256 no es válida");}}
	private static PublicKey parseEcPublicKey(String value)throws GeneralSecurityException{String normalized=value.replace("-----BEGIN PUBLIC KEY-----","").replace("-----END PUBLIC KEY-----","").replaceAll("\\s","");return KeyFactory.getInstance("EC").generatePublic(new X509EncodedKeySpec(Base64.getDecoder().decode(normalized)));}
	private void ensureFingerprintAvailable(String fingerprint,String excludedId){String sql="SELECT COUNT(*) FROM licensed_devices WHERE Public_Key_Fingerprint=:fingerprint"+(excludedId==null?"":" AND Id_Device<>:id");MapSqlParameterSource p=new MapSqlParameterSource("fingerprint",fingerprint);if(excludedId!=null)p.addValue("id",excludedId);Integer count=jdbc.queryForObject(sql,p,Integer.class);if(count!=null&&count>0)throw new BusinessValidationException("La clave pública ya está registrada en otro dispositivo");}
	private MapSqlParameterSource identityParams(String id,DeviceIdentity input,KeyIdentity key,LocalDateTime now){return new MapSqlParameterSource().addValue("id",id).addValue("uuid",id).addValue("name",trim(input.displayName())).addValue("manufacturer",trim(input.manufacturer())).addValue("model",trim(input.model())).addValue("android",trim(input.androidVersion())).addValue("androidId",trim(input.androidId())).addValue("packageName",input.packageName().trim()).addValue("appVersion",trim(input.appVersion())).addValue("publicKey",key.encoded()).addValue("fingerprint",key.fingerprint()).addValue("level",normalizeLevel(input.keySecurityLevel())).addValue("attestation",input.attestationAvailable()).addValue("now",Timestamp.valueOf(now));}
	private String normalizeLevel(String value){String level=value==null?"UNKNOWN":value.trim().toUpperCase(Locale.ROOT);return Set.of("SOFTWARE","TEE","STRONGBOX","UNKNOWN").contains(level)?level:"UNKNOWN";}
	private LicensedDevice device(String id){return persistence.findDevice(id).orElseThrow(()->new ResourceNotFoundException("Dispositivo no encontrado"));}
	private void event(String type,String result,String device,String application,String user,String license,String appVersion,String ip,String reason,String actor){jdbc.update("INSERT INTO license_validation_events(Id_Event,Id_Device,Id_Application,Id_Usuario,Id_License,Event_Type,Result,Reason,App_Version,Remote_IP,Created_At,Created_By) VALUES(:id,:device,:application,:user,:license,:type,:result,:reason,:version,:ip,:now,:actor)",new MapSqlParameterSource().addValue("id",uuid()).addValue("device",device).addValue("application",application).addValue("user",user).addValue("license",license).addValue("type",type).addValue("result",result).addValue("reason",reason).addValue("version",appVersion).addValue("ip",ip).addValue("now",Timestamp.valueOf(LocalDateTime.now())).addValue("actor",actor));}
	private String sha256(byte[] value){try{return HexFormat.of().withUpperCase().formatHex(MessageDigest.getInstance("SHA-256").digest(value));}catch(NoSuchAlgorithmException ex){throw new IllegalStateException(ex);}}
	private String normalizeCode(String value){return value.trim().toUpperCase(Locale.ROOT);}
	private String uuid(){return UUID.randomUUID().toString().toUpperCase(Locale.ROOT);}
	private String trim(String value){return value==null||value.isBlank()?null:value.trim();}
	private void required(String value,String message){if(value==null||value.isBlank())throw new BusinessValidationException(message);}
	private LocalDateTime time(Timestamp value){return value==null?null:value.toLocalDateTime();}

	public record DeviceIdentity(String displayName,String packageName,String publicKey,String androidId,String manufacturer,String model,String androidVersion,String appVersion,String keySecurityLevel,boolean attestationAvailable){}
	public record ManualDeviceCreated(LicensedDevice device,String enrollmentCode,LocalDateTime expiresAt){}
	public record EnrollmentCode(String code,LocalDateTime expiresAt){}
	public record Challenge(String challengeId,String deviceId,String nonce,LocalDateTime expiresAt){}
	public record Verification(String challengeId,String deviceId,boolean verified,LocalDateTime verifiedAt){}
	public record OperationalLicense(boolean valid,String operationalStatus,String licenseId,String deviceId,String applicationId,String userId,LocalDate validUntil){}
	public record OfflineCredential(String credential,String keyId,LocalDateTime issuedAt,LocalDate offlineValidUntil,LocalDate licenseValidUntil){}
	public record LicenseSession(String licenseId,String deviceId,String deviceFingerprint,long serverEpochMillis){}
	private record KeyIdentity(String encoded,String fingerprint){}
	private record EnrollmentRow(String id,String deviceId,LocalDateTime expiresAt,LocalDateTime usedAt,LocalDateTime revokedAt){}
	private record ChallengeRow(String nonce,String publicKey,LocalDateTime expiresAt,LocalDateTime usedAt,LocalDateTime credentialIssuedAt){}
	private record ApplicationIdentity(String id,LicensingMode mode){}
	private record LicenseRow(String applicationId,String userId,LocalDate validUntil,String packageName,LicensingMode mode,String deviceFingerprint){}
	private record AccessRow(LocalDate validUntil,int maxDevices){}
}
